# Generated by Django 4.0.2 on 2022-02-16 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='team/minzhi.png', null=True, upload_to='team/')),
                ('github', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('webpage', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('#ff689b', 'pink'), ('#e9bf06', 'yellow'), ('#3fcdc7', 'light-blue'), ('#41cf2e', 'green'), ('#d6ff22', 'light-green'), ('#4680ff', 'blue')], default='#3fcdc7', max_length=36)),
                ('icon', models.CharField(blank=True, choices=[('basketball-ball', 'basketball'), ('book', 'book'), ('file-alt', 'file'), ('tachometer-alt', 'tachometer'), ('globe-americas', 'global'), ('clock', 'clock')], max_length=36, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('delay', models.IntegerField(blank=True, default=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(blank=True, choices=[('app', 'app'), ('service', 'could service'), ('notebook', 'notebook')], max_length=36, null=True)),
                ('image', models.ImageField(blank=True, default='portfolio/design0.jpg', null=True, upload_to='portfolio/')),
                ('short_intro', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
